### ISSUE TITLE
RHEL 6.3 exhibits aberrant behavior on sudo cmd arg escaping

### ISSUE THREAD

**Issue by elentar** [worr/wsh#92]
Under RHEL 6.3, and apparently only under RHEL 6.3, command-line args being passed into sudo via the -U flag are not properly escaped. This is bizarre given the fact that you ship glib with the app. Old and newer releases of RHEL 6 do not exhibit this behavior.

**Comment by worr** [comment]
Dropping this issue as wontfix.
